version: '3'
services:
  server:
    build: ./server
    image: mastermobo/tutor-finder:server-latest
    environment:
      - PORT=3000
    depends_on:
      - database
  
  database:
    image: mongo
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foo
      - MONGO_INITDB_ROOT_PASSWORD=bar

  load-balancer:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /root/secrets/.certificate/meet-a-mentor.live.crt:/etc/nginx/ssl/meet-a-mentor.live.crt
      - /root/secrets/.certificate/meet-a-mentor.live.key:/etc/nginx/ssl/meet-a-mentor.live.key
      
volumes:
  mongo-db: