version: '3'
services:
  server:
    build: ./server
    image: mastermobo/tutor-finder:server-latest
    environment:
      - PORT=3000
    depends_on:
      - database
  
  database:
    image: mongo
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foo
      - MONGO_INITDB_ROOT_PASSWORD=bar

  load-balancer:
    image: nginx:stable-alpine

      
volumes:
  mongo-db: